efault: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: ''
  host: localhost
  pool: 5

development:
  <<: *default
  database: questionnaire_development

test:
  <<: *default
  database: questionnaire_test

production:
  <<: *default
  database: questionnaire_production
  username: questionnaire
  password: <%= ENV['QUESTIONNAIRE_DATABASE_PASSWORD'] %>

